server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true
  flyway:
    baseline-on-migrate: true
    check-location: true
    enabled: true
    locations: classpath:/db
    out-of-order: false
    validate-on-migrate: false

init:
  numberOfClients: 10